### ISSUE TITLE
Is it possible to add RTP protocol as an example?

### ISSUE THREAD

**Issue by pedoc** [enclave-networks/Enclave.FastPacket#10]
This protocol has a special case, that is, there may be padding data at the end of the real Payload.

```
 padding (P): 1 bit
      If the padding bit is set, the packet contains one or more
      additional padding octets at the end which are not part of the
      payload.  The last octet of the padding contains a count of how
      many padding octets should be ignored, including itself.  Padding
      may be needed by some encryption algorithms with fixed block sizes
      or for carrying several RTP packets in a lower-layer protocol data
      unit.
```

RFC https://www.ietf.org/rfc/rfc3550.txt

Is it possible to implement an example to demonstrate how to solve this kind of scenario?
Thanks

**Comment by enclave-alistair** [comment]
Can you use [function-based size determination](https://github.com/enclave-networks/Enclave.FastPacket#function-based-size-determination) to achieve this, and in that function inspect both the padding bit and the last octet of the payload to determine the size of the "actual" data?

**Comment by pedoc** [comment]
Thanks for the suggestion, I think this should work
Thanks 😄
